### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jla** [influxdata/influxdb-nodejs#3]
Hi!

I would like to give a try to this library and I was wondering about the status of the project and if it's going to be supported/maintained by InfluxData.

Thanks

**Comment by dubsky** [comment]
Hi,

this is still a pre-release version of the library and it is not yet published in npm. However, it is usable and if you discover a defect it will be fixed. 

In general, if you don't need high performance (lots of data points generated by a client, or having a large number of clients for InfluxDB), I would advise you to use https://github.com/node-influx/node-influx. It has lots of features but it lacks the ability send multiple data points with a single http request. Without that performance will be always bad.

This client is meant to be an enterprise-class solution with high performance and it will handle all InfluxDB specifics - handling reliability of the connection (buffering data when the server is not available, throttling the client when InfluxDB is overloaded by requests from other clients etc.). But we are not there fully yet.

Vlada
